export const constants = {
    MODIFY_MAIN_GRID_CODE: 'MODIFY_MAIN_GRID_CODE',
    MODIFY_MAIN_GRID_ITEM_CODE: 'MODIFY_MAIN_GRID_ITEM_CODE',
    DELETE_MAIN_GRID_ITEM: 'DELETE_MAIN_GRID_ITEM',
    ADD_MAIN_GRID_ITEM: "ADD_MAIN_GRID_ITEM",
    TOGGOLE_POPUP_EDITOR: "TOGGOLE_POPUP_EDITOR",

    MODIFY_DOCS_GRID_CODE: 'MODIFY_DOCS_GRID_CODE',
    MODIFY_DOCS_GRID_ITEM_CODE: 'MODIFY_DOCS_GRID_ITEM_CODE',
    DELETE_DOCS_GRID_ITEM: 'DELETE_DOCS_GRID_ITEM',
    ADD_DOCS_GRID_ITEM: "ADD_DOCS_GRID_ITEM",

    SELECT_ICON: 'SELECT_ICON'
};